### ISSUE TITLE
你好，这个具体是怎么用呢？

### ISSUE THREAD

**Issue by TimeIsGoOn** [webman-tech/amis-admin#8]
你好，这个具体是怎么用呢？后台已经部署好了，然后现在浏览器应该访问什么？

**Comment by krissss** [comment]
这个问题我怎么回答你呢。。。我不知道你碰到的具体问题是啥呀

参考下这个呢
https://github.com/krissss/webman-basic/tree/master/app/admin

**Comment by TimeIsGoOn** [comment]
谢谢，看到了，你是基于表结构，前端生成curd的amis的json，后端是AmisSourceController提供基于webman的资源路由接口。
